services:
  high_quality_image_captioner:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - 14080:80
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3




  
 
